### ISSUE TITLE
Unable to delete empty Mapping Entry

### ISSUE THREAD

**Issue by tomsquest** [alex1701c/JetBrainsRunner#11]
Given no Mapping Entry defined (but confirmed with one already define)
Given a new empty Mapping Entry (after a click on "Add new Mapping Entry")
When pressing the delete button on the empty Mapping Entry
Then the delete button has no effect
Expect: the delete button remove the empty Mapping Entry

![image](https://user-images.githubusercontent.com/365778/80566692-d9103e00-89f3-11ea-84e8-725525486189.png)

**Comment by alex1701c** [comment]
Thanks for reporting, it was just a signal I forgot to connect, this is fixed with the latest commit:
https://github.com/alex1701c/JetBrainsRunner/commit/386c14aa5266e9de8e923e86a016bb1d7f81d5af
