### ISSUE TITLE
Display the name of the project instead of its path

### ISSUE THREAD

**Issue by CLOVIS-AI** [alex1701c/JetBrainsRunner#12]
Hi! First of all, thanks a lot for this plugin, I've been searching for something like this for a while, and it works wonderfully!

By default, the plugin doesn't seem to understand the name of projects, though, only their path. For example, I name most my projects as 'Project Name (Context)' where 'Context' can be the name of the organization or something similar. This is how projects are displayed in the top of the screen in the apps and in the Toolbox.

As far as I see, there is no option in this plugin to enable this, which feels like a missed opportunity.

In most of my projects, I notice that JetBrains IDEs generate a file `.idea/.name` that contains this name, and this could be a very simple way to add the project name to this plugin. I'm not sure however if the `.name` file is always generated or if it's specific to only some IDEs (I only use IntelliJ, PyCharm & CLion).

I think it could be a good thing that this plugin would just read this file if it exists, and fallback to the directory name if it doesn't exist (just in case).

**Comment by alex1701c** [comment]
Thanks for the positive feedback!😃

I have quickly implement you request, the .`idea/.name` file is now the default name used and the directory name the fallback, see https://github.com/alex1701c/JetBrainsRunner/commit/ddb8777366189937b5c82f0d074baebc82011367.

**Comment by CLOVIS-AI** [comment]
Thanks a lot ^^ As soon as the AUR package is updated, I'll try it out and close this issue :)

**Comment by alex1701c** [comment]
I just want to add that I am not the maintainer of the AUR package.
So to try it out you could just build from source using the install script, this will works just as fine as the AUR.

**Comment by CLOVIS-AI** [comment]
Would you happen to know who is?

I'd rather keep using the AUR version so I can be sure all of my software is upgraded accordingly, but of course that's only valid if the AUR itself is updated regularly...

**Comment by alex1701c** [comment]
No, I don't know who it is, but it is up to date with the latest release.

But considering that you made a feature request I thought it would make sense that you try it out before releasing a new version of the plugin. But I am OK either way😃.

**Comment by CLOVIS-AI** [comment]
Is there something else planned before the next release?

**Comment by alex1701c** [comment]
The other issue should be fixed and then I will do the release.
Honestly I kinda forgot about this and was more actively contributing to KDE.

Edit: I am currently adapting the plugin to the new metadata system and fixing some clazy suggestions. The next release will be this week after some proper testing :-).
