### ISSUE TITLE
Add git to dependency's

### ISSUE THREAD

**Issue by QazCetelic** [alex1701c/JetBrainsRunner#13]
Git isn't included in the list of dependency's, and although most people will probaby have this installed some don't.

**Comment by alex1701c** [comment]
I actually thought about this but decided against it.

The list of dependencies contains the compile time and runtime dependencies of the plugin.
Git (and also Curl) are not needed and it should be pretty easy to install them if you don't have them already.

And if you download the .tar.gz file from the release page you don't need to have them installed to install the plugin/use the installer script.
