### ISSUE TITLE
Shorter name formatting

### ISSUE THREAD

**Issue by QazCetelic** [alex1701c/JetBrainsRunner#23]
%APP shortens the Application, but I suggest this for an even shorter version.

Example:
- %APPNAME: IntelliJ IDEA Community Edition
- %APP: IntelliJ IDEA CE
- %A: IntelliJ

**Comment by alex1701c** [comment]
IMHO I would just remove "IDEA" from the short name. If there is only one edition installed, I would argue that showing it does not provide any value.

**Comment by QazCetelic** [comment]
That works too

**Comment by alex1701c** [comment]
Okay, I will work on implementing it.

**Comment by alex1701c** [comment]
When one has both the community + ultimate editon:

![image](https://user-images.githubusercontent.com/38406607/154791666-863c1878-8852-4421-b346-c1f71d7f87f3.png)

When one has only one edition:
![image](https://user-images.githubusercontent.com/38406607/154811453-775d10cf-ccbf-46f9-963d-b226643522a9.png)

Does this look good to you?

**Comment by QazCetelic** [comment]
I think it would be better to leave out the edition if only one edition is installed.

**Comment by alex1701c** [comment]
Ups, I was planning to do a before/after, but then only posted the old screenshot :see_no_evil:

**Comment by alex1701c** [comment]
https://github.com/alex1701c/jetbrains-api/commit/7988a2e91d13106648f4c337d22f35ea72256c43


Please update the project to include this commit & the commit that updates the submodule

**Comment by alex1701c** [comment]
@QazCetelic What do you think? If I get no response I will commit those changes & make a new release

**Comment by QazCetelic** [comment]
I think it’s a good solution.
