### ISSUE TITLE
Install script doesn't install the latest version

### ISSUE THREAD

**Issue by QazCetelic** [alex1701c/JetBrainsRunner#26]
![image](https://user-images.githubusercontent.com/51381523/157383505-d14f9f92-ecf0-4c17-a893-c0ff6f72f6ed.png)

I tried to install the latest version using `curl https://raw.githubusercontent.com/alex1701c/JetBrainsRunner/master/install.sh | bash` but it installed version 1.7.1 instead of the latest version (1.8.0).

**Comment by alex1701c** [comment]
I assume https://github.com/alex1701c/JetBrainsRunner/pull/25 is the proposed fix for it?

**Comment by QazCetelic** [comment]
Not really, it was just a general improvement I noticed when trying to find what caused the issue.

**Comment by alex1701c** [comment]
What does the about dialog say about the version that is currently used? With master it says 1.8.0 on my system.

**Comment by QazCetelic** [comment]
I updated it through Discover, and now 1.8.0 is installed.

**Comment by alex1701c** [comment]
Though the dolphin version and KRunner plugin are completely separate.

**Comment by QazCetelic** [comment]
I meant Discover, but just opened dolphin and wrote the wrong thing.

**Comment by alex1701c** [comment]
Can this be considered resolved then?

**Comment by QazCetelic** [comment]
Yes
