### ISSUE TITLE
JetbrainsRunner opens an empty file instead of project

### ISSUE THREAD

**Issue by gschurck** [alex1701c/JetBrainsRunner#29]
I installed the last version of JetbrainsRunner 1.9.1, it finds the recent projects but each time it opens a blank file with the name of the project in LightEdit Mode, instead of opening the project. This behavior is for all the Jetbrains apps I tested (Pycharm Pro, IntelliJ Pro, Webstorm), all installed with Toolbox.

![image](https://user-images.githubusercontent.com/21091232/198886426-cb13436d-1f35-4c48-bc22-5e424d007a57.png)

I am on EndeavourOS KDE.

Any solution for this ?

Thanks.

**Comment by alex1701c** [comment]
I can not reproduce the issue with IntelliJ IDEA Ultimate. Please attach your ~/.config/JetBrains/IntelliJIdea2022.2/options/recentProjects.xml file so that I can try to reproduce the config constellation from your setup (hopefully the paths contain no sensitive information, otherwise please strip those entries out).

**Comment by gschurck** [comment]
Here for Webstorm 2022.2

```xml
<application>
  <component name="RecentProjectsManager">
    <option name="additionalInfo">
      <map>
        <entry key="$USER_HOME$/Personal Projects/the-software-graph/sg-frontend">
          <value>
            <RecentProjectMetaInfo frameTitle="sg-frontend – vite-env.d.ts" opened="true" projectWorkspaceId="2FDDIYph3gtJ4JD6fUe8UbWeYXj">
              <option name="activationTimestamp" value="1664017716803" />
              <option name="binFolder" value="$APPLICATION_HOME_DIR$/bin" />
              <option name="build" value="WS-222.4167.31" />
              <option name="buildTimestamp" value="1663152927381" />
              <frame x="0" y="0" width="2560" height="1404" extendedState="6" />
              <option name="productionCode" value="WS" />
              <option name="projectOpenTimestamp" value="1663956102879" />
            </RecentProjectMetaInfo>
          </value>
        </entry>
      </map>
    </option>
    <option name="lastOpenedProject" value="$USER_HOME$/Personal Projects/the-software-graph/sg-frontend" />
  </component>
</application>%       
```

**Comment by alex1701c** [comment]
I can confirm the issue. Thanks for the info!
