### ISSUE TITLE
Add config option to disable Update Checker

### ISSUE THREAD

**Issue by thigg** [alex1701c/JetBrainsRunner#3]
The Update Checker is a great idea.
It would be nice however, if it could be disabled.
Maybe make it configurable during install, or via config flag?

**Comment by alex1701c** [comment]
This is already planned 😃, I  would implement it as a checkbox in the config dialog. 
I will commit this as soon the custom configuration is finished (it is almost done by now).

**Comment by alex1701c** [comment]
![checkbox_disable_update_notifications](https://user-images.githubusercontent.com/38406607/67157053-e18e0a80-f326-11e9-98b7-25c9eb2ee1fc.png)

That is how I implemented it. The checkbox applies to the update notifications in the runner and the config dialog.

**Comment by thigg** [comment]
Cool!

**Comment by alex1701c** [comment]
Thanks !
