### ISSUE TITLE
Recent projects not found

### ISSUE THREAD

**Issue by voda** [alex1701c/JetBrainsRunner#34]
Hi, after some updates (of the plugin & JetBrains tools) the plugin didn't find any recent projects.

My setup:
* the runner installed from git, version 1.9.3
* JetBrains tools installed via JB toolbox (all latest versions)

I managed to fix the issues by changing the `Name=WebStorm 2022.3` to `Name=WebStorm` (removing the version from the name) in the `.desktop`. After this change, the plugin is able to find recent projects. Initially, it didn't work for PhpStorm either, but then I did purge some old cache/config (for older versions) from the toolbox. After that it started working for PhpStorm, I noticed the changed name and tried to change the name manually, which fixed it for WebStorm.

relevant runner logs:
```
Found /home/ondra/.local/share/applications/jetbrains-webstorm.desktop based on entry path
Found /home/ondra/.local/share/applications/jetbrains-phpstorm.desktop based on entry path
Found /home/ondra/.local/share/applications/jetbrains-goland.desktop based on entry path
Found /home/ondra/.local/share/applications/jetbrains-datagrip.desktop based on entry path
========== Manually Configured Jetbrains Applications ==========
Application path map: 
DataGrip 2022.3 ==> /home/ondra/.local/share/applications/jetbrains-datagrip.desktop
GoLand 2022.3 ==> /home/ondra/.local/share/applications/jetbrains-goland.desktop
PhpStorm ==> /home/ondra/.local/share/applications/jetbrains-phpstorm.desktop
WebStorm ==> /home/ondra/.local/share/applications/jetbrains-webstorm.desktop
========== Find Available Config Folders ==========
WebStorm /home/ondra/.config/JetBrains/WebStorm2022.3
PhpStorm /home/ondra/.config/JetBrains/PhpStorm2022.2
GoLand /home/ondra/.config/JetBrains/GoLand2022.2
DataGrip 2022.3 is not contained in alias
GoLand 2022.3 is not contained in alias
PhpStorm /home/ondra/.config/JetBrains/PhpStorm2022.2/options/
WebStorm /home/ondra/.config/JetBrains/WebStorm2022.3/options/
Config file found for PhpStorm /home/ondra/.config/JetBrains/PhpStorm2022.2/options/recentProjects.xml
Config file found for PhpStorm /home/ondra/.config/JetBrains/PhpStorm2022.2/options/recentProjects.xml
===== Recently used project folder for PhpStorm=====
   ** redacted, but contains the list of projects **

Config file found for WebStorm /home/ondra/.config/JetBrains/WebStorm2022.3/options/recentProjects.xml
Config file found for WebStorm /home/ondra/.config/JetBrains/WebStorm2022.3/options/recentProjects.xml
===== Recently used project folder for WebStorm=====
   ** redacted, but contains the list of projects **

========== Filter Jetbrains Apps ==========
Found not projects for: DataGrip 2022.3
Found not projects for: GoLand 2022.3
```

**Comment by alex1701c** [comment]
>Initially, it didn't work for PhpStorm either, but then I did purge some old cache/config (for older versions) from the toolbox.

What config dirs of PhpStorm did you have around before? The code is supposed to only use the latest version of the config folders.

>I managed to fix the issues by changing the Name=WebStorm 2022.3 to Name=WebStorm (removing the version from the name) in the .desktop. 

Yep, can reproduce this locally. I have pushed a fix already. Please check if this works (and be sure in src/jetbrains-api is the latest commit included, `git pull --recurse-submodules` should work for updating the submodule too).

**Comment by voda** [comment]
> What config dirs of PhpStorm did you have around before? The code is supposed to only use the latest version of the config folders.

I don't know, I don't have that data anymore. But probably this is not related to the issue.

> Yep, can reproduce this locally. I have pushed a fix already. Please check if this works (and be sure in src/jetbrains-api is the latest commit included, `git pull --recurse-submodules` should work for updating the submodule too).

The fix works, now the plugin finds also projects from GoLand, which has the `GoLand 2022.3` as the name in the .desktop file.

Thanks for fixing it and thanks for the plugin.

**Comment by alex1701c** [comment]
Thanks for confirming the fix! I will make a new release and update https://www.pling.com/p/1311630/.
