### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by thigg** [alex1701c/JetBrainsRunner#4]
When I launch a project via the JetBrainsRunner I get a:

> cannot find file %u

error everytime. After clicking that away, everything starts fine.

The info tooltip says I am using version 0.1

**Comment by alex1701c** [comment]
Can you please check if the latest commit fixes the issue ?

**Comment by thigg** [comment]
Yes, it does.

**Comment by thigg** [comment]
Will you create a release with that soon?

**Comment by alex1701c** [comment]
Yes but I am very busy at the moment and want to make some other minor improvements to the project 🙃
