### ISSUE TITLE
Mention Arch Linux package in readme

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsRunner#40]
Hello, thank you for this plugin!
I have created an AUR package for it https://aur.archlinux.org/packages/plasma5-runners-jetbrains-runner-git. Can you please mention this in readme (and possibly in KDE store)?

**Comment by alex1701c** [comment]
That is a good idea & thanks for packaging. Looking at the script, it seems like KRunner has to be restarted for the new plugin to be loaded?

**Comment by Ashark** [comment]
I do that in install script (it resides sibling to PKGBUILD), as instructed in readme, and as it is done in install.sh.
However, in the install.sh you also do start krunner, which is not instructed in readme.
I had not problem to open kruner with alt + f2 after killing it, so I did not included that command in the post_install function.

**Comment by alex1701c** [comment]
> I had not problem to open kruner with alt + f2 after killing it, so I did not included that command in the post_install function.

Yeah, that was only relevant for really old Plasma versions where KRunner was not yet DBus activated.
