### ISSUE TITLE
The apply button works improperly in runner settings

### ISSUE THREAD

**Issue by Ashark** [alex1701c/JetBrainsRunner#43]
I was changing the format string to "project" instead of "launch", and  when I press the Apply button, it was not deactivating:
![image](https://github.com/alex1701c/JetBrainsRunner/assets/22634975/fd5f63d0-25d7-4c69-abf6-8014f74d2c29)

**Comment by alex1701c** [comment]
But the saving itself worked?

I will look into this when I am bavk from vacation :)

**Comment by alex1701c** [comment]
c4b918cac8f03ae936c8e0a77ec06898cb42f9e5 Should fix it!

**Comment by Ashark** [comment]
Yeah, works, thanks!
