### ISSUE TITLE
Issue installing in Plasma 6

### ISSUE THREAD

**Issue by koenhendriks** [alex1701c/JetBrainsRunner#44]
When installing I first ran into the following issue:

```sh
Error while loading shared libraries: libpackagekitqt6.so.1
```

This was fixed by installing `packagekit-qt6`. Now it runs the install script but I'm running into the following error:
```sh
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/qt6/plugins/kcm_krunner_jetbrainsrunner.so
-- Installing: /usr/lib/qt6/plugins/kf6/krunner/krunner_jetbrainsrunner.so
-- Installing: /usr/share/pixmaps/jetbrainsrunner.png
"Quitting application krunner failed. Error reported was:\n\n     org.freedesktop.DBus.Error.NoReply : Remote peer disconnected"
```

**Comment by alex1701c** [comment]
But that is not a dependency of this project. Maybe it gets pulled in by some other place?

**Comment by alex1701c** [comment]
Please check if the normal KRunner opens - I think this isssue is unrelated to the project
