### ISSUE TITLE
Search by Project name instead of directory name

### ISSUE THREAD

**Issue by vguardiola** [alex1701c/JetBrainsRunner#7]
I have a some projects that the directory name is the same, but not the path obviously. Andthe project name is the name that I see in the toolbox's project list

**Comment by alex1701c** [comment]
Hello,
I have added an option which allows you to use the path of the project in the KRunner text.

This is how it can be configured and how it looks:
![jbr_issue](https://user-images.githubusercontent.com/38406607/77773727-4ffb9500-704a-11ea-9d03-58d7bfcbcc3f.png)


Is this what you had in mind?

**Comment by vguardiola** [comment]
Hi, I've a directory structure like this:
/home/me/maindirofaproject/code/api/current
/home/me/maindirofaproject/code/www/current
/home/me/maindirofaproject/code/backend/current

Each folder on my IDE is a different project and each has a project name like api.maindirofaproject, www.maindirofaproject ...

And only get result if I search current, no results if I search by api or www or maindirofaproject.

I was looking the xml that you use for search and I think that my suggestion is more complicate because the xml don't have this project name.

I suppose that Toolbox use the name of the file with extension .iml inside of .idea folder on each project

Thanks

**Comment by alex1701c** [comment]
Hey,
currently the plugin check if the last directory (in your case always `current`) starts with the query.
Thats because I wanted to avoid showing lots of results if the user wants results from other plgins.

I have just created a little branch which checks if the full path contains the query, this will show results for queries like `backend`. https://github.com/alex1701c/JetBrainsRunner/tree/search_path
Hopefully this helps 😃

**Comment by thigg** [comment]
I was just about to submit a feature reuest for this. The idea with the formatter is very handy!
I just tried it quickly with %APP, that wasn't replaced, but everything else works.

(Removed it alltogether anyway, the icon is enough for me)

Thanks for your work!

**Comment by alex1701c** [comment]
Thanks for the appreciation and the info, I quickly fixed this.

Edit: I have implemented a GUI option to change the search behavior.
