### ISSUE TITLE
Wrong version number in the settings

### ISSUE THREAD

**Issue by delta-one** [alex1701c/JetBrainsRunner#8]
Hi,

I'm running Debian Testing and installed the deb-file of the newest version (1.4.0). 
```
ii  krunner-jetbrainsrunner 1.4.0        amd64        A Krunner Plugin which allows you to open your recent projects
```
But in the settings, the version number is wrong and asks me to update:
```
Updates Available !
Current Version: 1.2.2
1.4.0: New filter and formatting options
Please go to https://github.com/alex1701c/JetBrainsRunner
and get the latest version
```

**Comment by alex1701c** [comment]
Yep, I forgot to change this.

Now the version number gets once defined in the CMakeLists.txt and is reused, so that this does not happen again 🙃
