### ISSUE TITLE
Compatibility with 2020.1

### ISSUE THREAD

**Issue by delta-one** [alex1701c/JetBrainsRunner#9]
Hi,

I'm running the latest 2020.1 editions of e.g. CLion and Webstorm. The latest version 1.4.1 on Debian Testing of this app seemingly doesn't find any projects for the 2020.1 editions. It did work fine a week ago with CLion 2019.3, but after the upgrade to 2020.1 no more projects are shown in Krunner.

The logfile output is:
```
========== Find Available Config Folders ==========
========== Filter Jetbrains Apps ==========
Found not projects for: CLion
Found not projects for: IntelliJ IDEA Community
Found not projects for: WebStorm
```

**Comment by alex1701c** [comment]
I have found the issue: They have changed the locations and directory structure of the config directories.

I am already writing a patch, it should be done tomorrow 😃

**Comment by alex1701c** [comment]
I have made  quick fix https://github.com/alex1701c/JetBrainsRunner/tree/fix_new_file_locations
can you check if that works for you too? (Please make sure that you get the latest state of the jetbains-api submodule).

I want to make a few tests and code improvements before pushing this to the master and making a release for both plugins.

**Comment by delta-one** [comment]
Jepp, it does indeed work. It finds now all the projects.
